In [ ]:
%pip install opencv-python
%pip install pandas

In [17]:
import os
import cv2
from glob import glob
import pandas as pd
import numpy as np

In [18]:
img_lst = glob('C:/Users/admin/Desktop/tester/*.jpg')
label_lst = glob('C:/Users/admin/Desktop/tester/*.txt')
print(len(img_lst))
print(len(label_lst))

7847
7847

In [3]:
comp_img = img_lst.copy()
comp_label = label_lst.copy()
print(len(comp_img))
print(len(comp_label))

7847
7848

In [4]:
new_comp_img=[]
for i in range(len(comp_img)):
  new_comp_img.append(comp_img[i].split('.'))

new_comp_label=[]
for i in range(len(comp_label)):
  new_comp_label.append(comp_label[i].split('.'))


print(new_comp_img[10])
print(new_comp_label[10])

['C:/Users/admin/Desktop/tester\\gray_ttp2_1006', 'jpg']
['C:/Users/admin/Desktop/tester\\gray_ttp2_1006', 'txt']

In [5]:
df_comp_img = pd.DataFrame(new_comp_img)
df_comp_label = pd.DataFrame(new_comp_label)

df_comp_img.columns = ['name', 'exten']
df_comp_label.columns = ['name', 'exten']

In [6]:
df_comp_img.head()

                                           name exten
0     C:/Users/admin/Desktop/tester\gray_ttp2_0   jpg
1     C:/Users/admin/Desktop/tester\gray_ttp2_1   jpg
2    C:/Users/admin/Desktop/tester\gray_ttp2_10   jpg
3   C:/Users/admin/Desktop/tester\gray_ttp2_100   jpg
4  C:/Users/admin/Desktop/tester\gray_ttp2_1000   jpg

In [7]:
df_comp_label.head()

                                           name exten
0     C:/Users/admin/Desktop/tester\gray_ttp2_0   txt
1     C:/Users/admin/Desktop/tester\gray_ttp2_1   txt
2    C:/Users/admin/Desktop/tester\gray_ttp2_10   txt
3   C:/Users/admin/Desktop/tester\gray_ttp2_100   txt
4  C:/Users/admin/Desktop/tester\gray_ttp2_1000   txt

In [8]:
df_comp_img.drop('exten', axis=1, inplace=True)

In [9]:
df_comp_img.head()

                                           name
0     C:/Users/admin/Desktop/tester\gray_ttp2_0
1     C:/Users/admin/Desktop/tester\gray_ttp2_1
2    C:/Users/admin/Desktop/tester\gray_ttp2_10
3   C:/Users/admin/Desktop/tester\gray_ttp2_100
4  C:/Users/admin/Desktop/tester\gray_ttp2_1000

In [10]:
df_comp_label.drop('exten', axis=1, inplace=True)

In [11]:
df_comp_label.head()

                                           name
0     C:/Users/admin/Desktop/tester\gray_ttp2_0
1     C:/Users/admin/Desktop/tester\gray_ttp2_1
2    C:/Users/admin/Desktop/tester\gray_ttp2_10
3   C:/Users/admin/Desktop/tester\gray_ttp2_100
4  C:/Users/admin/Desktop/tester\gray_ttp2_1000

In [12]:
def GetDifferences(df1, df2):
  df = pd.concat([df1, df2]).reset_index(drop=True)
  idx = [diff[0] for diff in df.groupby(list(df.columns)).groups.values() if len(diff) == 1]
  return df.reindex(idx)

In [13]:
answer = GetDifferences(df_comp_label, df_comp_img)
print(len(answer))

1

In [14]:
answer

                                          name
2423  C:/Users/admin/Desktop/tester\gray_ttp_7

In [120]:
#answer['exten'] = 'jpg' #이미지 정제
answer['exten'] = 'txt'#텍스트 정제

In [16]:
answer.head()

                                          name
2423  C:/Users/admin/Desktop/tester\gray_ttp_7

In [122]:
answer["Full Name"] = answer["name"].map(str) + "." + answer["exten"]

In [123]:
answer.head()

,name,exten,Full Name
581,C:/Users/admin/Desktop/data_V2\ttp2_154,txt,C:/Users/admin/Desktop/data_V2\ttp2_154.txt

In [124]:
answer.drop('name', axis=1, inplace=True)
answer.drop('exten', axis=1, inplace=True)
answer.head()

                                       Full Name
581  C:/Users/admin/Desktop/data_V2\ttp2_154.txt

In [125]:
for i in answer['Full Name']:
    if os.path.isfile(i):
        os.remove(i)
        print('removed')

removed